### ISSUE TITLE
Error when cloning

### ISSUE THREAD

**Issue by muriloasouza** [rdeits/CouenneNL.jl#2]
Hello, i got the following error:

```
julia> Pkg.clone("https://github.com/rdeits/CounneNL.jl")
INFO: Cloning CounneNL from https://github.com/rdeits/CounneNL.jl
ERROR: GitError(Code:ERROR, Class:Net, Request failed with status code: 404)
```

When i type the "Pkg.clone...." comand, it asks me for my Github username and password. I type them, then i get that error.

**Comment by rdeits** [comment]
What version of Julia are you using, and on what operating system?

**Comment by muriloasouza** [comment]
Julia 0.6.3 on a Windows 10

**Comment by rdeits** [comment]
Oh, you just have a typo. You have `CounneNL.jl`, but you want `CouenneNL.jl`.

**Comment by muriloasouza** [comment]
Omg... thanks, i didn't even noticed that. I just copied it from the "Installation" guide from the main page:

https://github.com/rdeits/CouenneNL.jl

**Comment by rdeits** [comment]
Whoops, thanks for pointing that out. I've fixed the typo.
